exp_name: linear_resnet152
dataset: awa2
concepts: attr
load_model: False
debug: False

type: transformer
linear: False
neg_sample: 0
model: resnet152
pretrained: True
freeze: True

exp_times: 3
start_epoch: 1
end_epoch: 21

l_rate: 5e-5
optim: Adam
momentum: 0.9

calibration_gamma: 0

k: 30
d:
  bert:
    apy: 768
    awa2: 768
    sun: 768
    cub: 768
  attr:
    apy: 64
    awa2: 85
    sun: 102
    cub: 312

train_batch_size: 512
test_batch_size: 640
